[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
strict_optional = true
disallow_untyped_defs = false  # 段階的導入のため最初は緩い設定
ignore_missing_imports = true  # 外部ライブラリの型情報不足を一時的に許可

# utils/json-validator/ ディレクトリを対象とする
files = ["utils/json-validator/validator/", "utils/json-validator/tests/"]

# 段階的に厳密化するための設定
[[tool.mypy.overrides]]
module = "utils.json-validator.validator.*"
disallow_untyped_defs = true

[tool.black]
line-length = 88
target-version = ['py313']
include = '\.pyi?$'
extend-exclude = '''
/(
  # 外部生成ファイルを除外
  site/
)/
'''