name: Deploy JOCF Documentation to GitHub Pages

on:
  push:
    branches:
      - main
      - feature/md-autogen # FIXME: デバッグのため、作業ブランチを一時的に追加
    paths:
      # ドキュメント、GitHub Actions、MkDocsの設定ファイルに変更があった場合のみ実行
      - 'docs/**'
      - '.github/workflows/deploy-gh-pages.yml'
      - 'mkdocs.yml'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. チェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. キャッシュ
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 3. Python環境をセットアップ
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. MkDocsのビルド
      - name: Build MkDocs site
        run: mkdocs build --strict

      # 5. GitHub Pagesにデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature/md-autogen' # FIXME: デバッグのため、作業ブランチを一時的に追加
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # デプロイ先のブランチを指定
          publish_dir: site # ビルド成果物のディレクトリを指定
          force_orphan: true # ブランチの履歴を保持しない(都度作り直し)